@GameLibraryApi = http://localhost:5077



### AUTH
### 
POST {{GameLibraryApi}}/auth/login?useCookies=true
Content-Type: application/json

{
  "email": "oskar.eriksson@skoglit.se",
  "password": "1234"
}



### ITEMS
### 
GET {{GameLibraryApi}}/items/?search=5

### 
GET {{GameLibraryApi}}/items/2

### 
PUT {{GameLibraryApi}}/items/2
Content-Type: application/json

{
  "name": "Item 2cc",
  "description": "Item 2cc description"
}

### 
PUT {{GameLibraryApi}}/items/2/status
Content-Type: application/json

2

### 
POST {{GameLibraryApi}}/items/
Content-Type: application/json

{
  "name": "Item 13",
  "description": "Item 13 description",
  "status": 1,
  "youtubeUrl": "123"
}

### 
DELETE {{GameLibraryApi}}/items/22



### DETAILS
### 
GET {{GameLibraryApi}}/items/1/details

### 
GET {{GameLibraryApi}}/items/1/details/2

### 
PUT {{GameLibraryApi}}/items/1/details/2
Content-Type: application/json

{
  "detail": "Detail 2bb"
}

### 
POST {{GameLibraryApi}}/items/1/details
Content-Type: application/json

{
  "detail": "Detail 6"
}

###
DELETE {{GameLibraryApi}}/items/1/details/6